# This workflow will build a Swift project and its DocC documentation
name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-latest

    steps:
    # Swift build step
    - uses: actions/checkout@v4
    - name: 🔨 Build
      run: swift build -v

    # Swift documentation step
    - uses: fwcd/swift-docc-action@v1
    - name: 📜 Build Documentation
      uses: fwcd/swift-docc-action@v1
      with:
        target: SwordRPC
        output: ./public
        transform-for-static-hosting: 'true'
        disable-indexing: 'true'
        hosting-base-path: SwordRPC
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public

  # GH pages deploy if on master
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    if: github.ref == 'refs/heads/master'
    steps:
    - name: Deploy Docs
      uses: actions/deploy-pages@v4
